name: Tests
on:
  push:
    branches: [ ci ]
      # - 'cissie_dev'
      # - 'main'

concurrency:
  group: testing-$${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Unit tests for torch_plugin, surrogate
  basic-env-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  # Examples with baisc env
  # Julia unit tests and examples with julia env
  # GPU examples on ifarm (self-host runner, singularity image)
