name: Tests
on:
  push:
    branches:
      - 'cissie_dev'
      - 'main'

concurrency:
  group: testing-$${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # spack_env: [basic, julia, g4]
        spack_env: [basic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
